---
kind: "operation"
client: "rug-cli 0.28.0"
generator:
  name: "NewRugProject"
  group: "atomist-rugs"
  artifact: "rug-editors"
  version: "0.22.0"
  origin:
    repo: "https://github.com/atomist-rugs/rug-editors.git"
    branch: "1e6a9f0f941441a2d3b461d7af3ce803b2e3c845"
    sha: "1e6a9f0"
  parameters:
    - "project_name": "release-rugs"
    - "owner": "atomist-rugs"
    - "description": "handlers and editors for cutting a release"
    - "version": "0.1.0"

---
kind: "operation"
client: "rug-cli 0.28.0"
editor:
  name: "AddTypeScript"
  group: "atomist-rugs"
  artifact: "rug-editors"
  version: "0.22.0"
  origin:
    repo: "https://github.com/atomist-rugs/rug-editors.git"
    branch: "1e6a9f0f941441a2d3b461d7af3ce803b2e3c845"
    sha: "1e6a9f0"

